// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfxmpjnhhcfyxkxhwjfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmeG1wam5oaGNmeXhreGh3amZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzI1MDgsImV4cCI6MjA3MDA0ODUwOH0.7K-ZxyPGfWYpZW9zZuSyapDeA4lKAJe8QU8YAMZ59X8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});